// <auto-generated />
namespace AIMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newinit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newinit));
        
        string IMigrationMetadata.Id
        {
            get { return "201612301509134_new init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
