// <auto-generated />
namespace AIMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alteredEntityProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteredEntityProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201612281536230_altered EntityProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
